const API='https://suvsqzlemwsmqelxivjw.supabase.co/functions/v1/cleancontrol-api-v3';
const NOTIFY_API='https://suvsqzlemwsmqelxivjw.supabase.co/functions/v1/cleancontrol-notify';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function storageGet(k){try{return localStorage.getItem(k)||''}catch{return ''}}
function storageSet(k,v){try{localStorage.setItem(k,v);return true}catch{return false}}
function storageRemove(k){try{localStorage.removeItem(k)}catch{}}
let token=storageGet('cc_token'), me=null, boot=null, currentRound=null, lastLoginPassword='', notifyTimer=null, notifySince='';
const views={};
function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';clearTimeout(toast._t);toast._t=setTimeout(()=>t.style.display='none',2600)}
function modal(html){$('modalRoot').innerHTML=`<div class="modal"><div class="box">${html}</div></div>`}
function closeModal(){$('modalRoot').innerHTML=''}
function net(){const n=$('netState');if(!n)return;n.textContent=navigator.onLine?'متصل':'بدون إنترنت';n.classList.toggle('offline',!navigator.onLine);if(typeof updatePending==='function')updatePending()}
addEventListener('online',()=>{net();if(typeof syncQueue==='function')syncQueue();pollNotifications()}); addEventListener('offline',net); net();
async function api(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data})}); const j=await r.json().catch(()=>({ok:false,error:'استجابة غير صالحة'})); if(!r.ok||j.ok===false){const e=new Error(j.error||'تعذر تنفيذ الطلب');e.code=j.code;e.status=r.status;throw e} return j}
async function notifyApi(data={}){const r=await fetch(NOTIFY_API,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(data)});const j=await r.json().catch(()=>({ok:false,error:'استجابة غير صالحة'}));if(!r.ok||j.ok===false){const e=new Error(j.error||'تعذر فحص الإشعارات');e.code=j.code;throw e}return j}
async function login(){const u=$('loginUser').value.trim(),p=$('loginPass').value;$('loginMsg').textContent='جاري الدخول...';try{const j=await api('login',{username:u,password:p});token=j.token;storageSet('cc_token',token);me=j.user;lastLoginPassword=p;await afterLogin()}catch(e){lastLoginPassword='';$('loginMsg').textContent=e?.message||'تعذر تسجيل الدخول'}}
function stopNotificationWatcher(){if(notifyTimer){clearInterval(notifyTimer);notifyTimer=null}}
function logout(){stopNotificationWatcher();token='';me=null;boot=null;lastLoginPassword='';storageRemove('cc_token');$('app').classList.add('hidden');$('loginCard').classList.remove('hidden');$('loginPass').value=''}
async function afterLogin(){try{const j=await api('bootstrap');boot=j;me=j.user;$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');buildNav();if(me.must_change_password)return forcePassword();lastLoginPassword='';const target=new URLSearchParams(location.search).get('view');if(target==='notes')await notes();else await home();if(typeof syncQueue==='function')syncQueue();if(me.role==='supervisor'){startNotificationWatcher();setTimeout(maybePromptNotifications,500)}}catch(e){if(e.code==='PASSWORD_CHANGE_REQUIRED')return forcePassword();logout();$('loginMsg').textContent=e?.message||'تعذر تحميل الحساب'}}
function notificationSupported(){return 'Notification'in window&&'serviceWorker'in navigator}
window.enableNotifications=async function(){const m=$('notifyPermissionMsg');try{if(!notificationSupported())throw new Error('هذا المتصفح لا يدعم إشعارات النظام');const permission=await Notification.requestPermission();if(permission!=='granted'){if(m)m.textContent='لم يتم السماح بالإشعارات. فعّلها من إعدادات المتصفح للموقع.';return}storageSet('cc_notify_enabled','1');closeModal();toast('تم تفعيل الإشعارات');beep();navigator.vibrate?.([120,80,120]);await showSystemNotification('تم تفعيل إشعارات CleanControl','ستصلك تنبيهات عند وصول ملاحظة جديدة من الإدارة.','test');pollNotifications()}catch(e){if(m)m.textContent=e?.message||'تعذر تفعيل الإشعارات'}}
function maybePromptNotifications(){if(me?.role!=='supervisor'||!notificationSupported())return;if(Notification.permission==='granted'){storageSet('cc_notify_enabled','1');return}if(Notification.permission==='denied'){toast('الإشعارات محظورة من إعدادات المتصفح');return}modal(`<h3>تفعيل إشعارات CleanControl</h3><p class="notice">فعّل الإشعارات حتى يظهر تنبيه على الهاتف مع اهتزاز وصوت النظام عند وصول ملاحظة جديدة من الإدارة.</p><button class="primary" style="width:100%" onclick="enableNotifications()">تفعيل الإشعارات</button><button class="secondary" style="width:100%;margin-top:8px" onclick="closeModal()">لاحقًا</button><div id="notifyPermissionMsg" class="small" style="margin-top:8px"></div>`)}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.12,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.35);o.start();o.stop(c.currentTime+.35);setTimeout(()=>c.close(),500)}catch{}}
async function showSystemNotification(title,body,tag='cleancontrol-note'){if(!notificationSupported()||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag,renotify:true,vibrate:[220,100,220,100,320],requireInteraction:true,data:{url:'./?view=notes'}})}catch{try{new Notification(title,{body,tag})}catch{}}}
function startNotificationWatcher(){stopNotificationWatcher();notifySince=storageGet('cc_notify_since')||new Date(Date.now()-120000).toISOString();pollNotifications();notifyTimer=setInterval(pollNotifications,20000)}
async function pollNotifications(){if(!token||me?.role!=='supervisor'||!navigator.onLine)return;try{const j=await notifyApi({action:'poll',since:notifySince});if(j.server_time){notifySince=j.server_time;storageSet('cc_notify_since',notifySince)}for(const n of j.notes||[]){const pri=n.priority==='urgent'?'عاجلة':n.priority==='high'?'عالية':'جديدة';const place=[n.buildings?.name,n.floors?.label].filter(Boolean).join(' — ');beep();navigator.vibrate?.([220,100,220,100,320]);toast(`ملاحظة ${pri} من الإدارة`);await showSystemNotification('CleanControl — ملاحظة من الإدارة',`${n.note_text}${place?' • '+place:''}`,`note-${n.id}`)}}catch(e){if(e.code==='SESSION_EXPIRED')stopNotificationWatcher()}}
function buildNav(){const admin=me?.role==='admin';const buttons=[['home','الرئيسية'],['notes','الملاحظات'],...(admin?[['operations','مركز العمليات'],['checklists','Checklist'],['profiles','المشرفون'],['schedules','خطة الجولات'],['reports','التقارير'],['audit','سجل التدقيق']]:[]),['settings','الإعدادات']];$('nav').innerHTML=buttons.map(([k,l])=>`<button data-nav="${k}">${l}</button>`).join('')+`<button class="danger" id="logoutBtn">خروج</button>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));$('logoutBtn').onclick=logout}
function activeNav(k){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===k))}
async function go(k){activeNav(k);if(k==='home')return home();if(k==='notes')return notes();if(k==='operations')return operations();if(k==='checklists')return checklists();if(k==='profiles')return profiles();if(k==='schedules')return schedules();if(k==='reports')return reports();if(k==='audit')return auditLog();if(k==='settings')return settings()}
function validNewPassword(p){return p.length>=8&&/[A-Za-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
function forcePassword(){if(!lastLoginPassword){logout();$('loginMsg').textContent='سجّل الدخول مرة أخرى لتغيير كلمة المرور بأمان';return}modal(`<h3>تغيير كلمة المرور مطلوب</h3><p class="notice">اكتب كلمة المرور الجديدة مرتين فقط.<br><b>الشروط:</b> 8 خانات على الأقل + حرف إنجليزي + رقم + رمز مثل @ أو !</p><input id="newp" type="password" placeholder="كلمة المرور الجديدة" autocomplete="new-password"><div style="height:8px"></div><input id="newp2" type="password" placeholder="تأكيد كلمة المرور الجديدة" autocomplete="new-password"><div style="height:12px"></div><button class="primary" id="forceSave" style="width:100%">حفظ ومتابعة</button><div id="forceMsg" class="small" style="margin-top:8px"></div>`);$('forceSave').onclick=async()=>{const b=$('newp').value,c=$('newp2').value,m=$('forceMsg');if(b!==c){m.textContent='كلمتا المرور غير متطابقتين';return}if(!validNewPassword(b)){m.textContent='استخدم 8 خانات على الأقل مع حرف إنجليزي ورقم ورمز مثل @';return}if(b===lastLoginPassword){m.textContent='اختر كلمة مرور جديدة مختلفة عن الحالية';return}const btn=$('forceSave');btn.disabled=true;m.textContent='جاري حفظ كلمة المرور...';try{const j=await api('change_password',{old_password:lastLoginPassword,new_password:b});token=j.token;storageSet('cc_token',token);lastLoginPassword='';closeModal();await afterLogin();toast('تم تغيير كلمة المرور بنجاح')}catch(e){m.textContent=e?.message||'تعذر تغيير كلمة المرور';btn.disabled=false}}}