const API='https://suvsqzlemwsmqelxivjw.supabase.co/functions/v1/cleancontrol-api-v3';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]));
function storageGet(k){try{return localStorage.getItem(k)||''}catch{return ''}}
function storageSet(k,v){try{localStorage.setItem(k,v);return true}catch{return false}}
function storageRemove(k){try{localStorage.removeItem(k)}catch{}}
let token=storageGet('cc_token'), me=null, boot=null, currentRound=null, lastLoginPassword='';
const views={};
function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';clearTimeout(toast._t);toast._t=setTimeout(()=>t.style.display='none',2600)}
function modal(html){$('modalRoot').innerHTML=`<div class="modal"><div class="box">${html}</div></div>`}
function closeModal(){$('modalRoot').innerHTML=''}
function net(){const n=$('netState');if(!n)return;n.textContent=navigator.onLine?'متصل':'بدون إنترنت';n.classList.toggle('offline',!navigator.onLine);if(typeof updatePending==='function')updatePending()}
addEventListener('online',()=>{net();if(typeof syncQueue==='function')syncQueue()}); addEventListener('offline',net); net();
async function api(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data})}); const j=await r.json().catch(()=>({ok:false,error:'استجابة غير صالحة'})); if(!r.ok||j.ok===false){const e=new Error(j.error||'تعذر تنفيذ الطلب');e.code=j.code;e.status=r.status;throw e} return j}
async function login(){const u=$('loginUser').value.trim(),p=$('loginPass').value;$('loginMsg').textContent='جاري الدخول...';try{const j=await api('login',{username:u,password:p});token=j.token;storageSet('cc_token',token);me=j.user;lastLoginPassword=p;await afterLogin()}catch(e){lastLoginPassword='';$('loginMsg').textContent=e?.message||'تعذر تسجيل الدخول'}}
function logout(){token='';me=null;boot=null;lastLoginPassword='';storageRemove('cc_token');$('app').classList.add('hidden');$('loginCard').classList.remove('hidden');$('loginPass').value=''}
async function afterLogin(){try{const j=await api('bootstrap');boot=j;me=j.user;$('loginCard').classList.add('hidden');$('app').classList.remove('hidden');buildNav();if(me.must_change_password)return forcePassword();lastLoginPassword='';await home();if(typeof syncQueue==='function')syncQueue()}catch(e){if(e.code==='PASSWORD_CHANGE_REQUIRED')return forcePassword();logout();$('loginMsg').textContent=e?.message||'تعذر تحميل الحساب'}}
function buildNav(){const admin=me?.role==='admin';const buttons=[['home','الرئيسية'],['notes','الملاحظات'],...(admin?[['operations','مركز العمليات'],['checklists','Checklist'],['profiles','المشرفون'],['schedules','خطة الجولات'],['reports','التقارير'],['audit','سجل التدقيق']]:[]),['settings','الإعدادات']];$('nav').innerHTML=buttons.map(([k,l])=>`<button data-nav="${k}">${l}</button>`).join('')+`<button class="danger" id="logoutBtn">خروج</button>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));$('logoutBtn').onclick=logout}
function activeNav(k){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===k))}
async function go(k){activeNav(k);if(k==='home')return home();if(k==='notes')return notes();if(k==='operations')return operations();if(k==='checklists')return checklists();if(k==='profiles')return profiles();if(k==='schedules')return schedules();if(k==='reports')return reports();if(k==='audit')return auditLog();if(k==='settings')return settings()}
function validNewPassword(p){return p.length>=8&&/[A-Za-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
function forcePassword(){if(!lastLoginPassword){logout();$('loginMsg').textContent='سجّل الدخول مرة أخرى لتغيير كلمة المرور بأمان';return}modal(`<h3>تغيير كلمة المرور مطلوب</h3><p class="notice">اكتب كلمة المرور الجديدة مرتين فقط.<br><b>الشروط:</b> 8 خانات على الأقل + حرف إنجليزي + رقم + رمز مثل @ أو !</p><input id="newp" type="password" placeholder="كلمة المرور الجديدة" autocomplete="new-password"><div style="height:8px"></div><input id="newp2" type="password" placeholder="تأكيد كلمة المرور الجديدة" autocomplete="new-password"><div style="height:12px"></div><button class="primary" id="forceSave" style="width:100%">حفظ ومتابعة</button><div id="forceMsg" class="small" style="margin-top:8px"></div>`);$('forceSave').onclick=async()=>{const b=$('newp').value,c=$('newp2').value,m=$('forceMsg');if(b!==c){m.textContent='كلمتا المرور غير متطابقتين';return}if(!validNewPassword(b)){m.textContent='استخدم 8 خانات على الأقل مع حرف إنجليزي ورقم ورمز مثل @';return}if(b===lastLoginPassword){m.textContent='اختر كلمة مرور جديدة مختلفة عن الحالية';return}const btn=$('forceSave');btn.disabled=true;m.textContent='جاري حفظ كلمة المرور...';try{const j=await api('change_password',{old_password:lastLoginPassword,new_password:b});token=j.token;storageSet('cc_token',token);lastLoginPassword='';closeModal();await afterLogin();toast('تم تغيير كلمة المرور بنجاح')}catch(e){m.textContent=e?.message||'تعذر تغيير كلمة المرور';btn.disabled=false}}}