const SCHEDULE_API='https://suvsqzlemwsmqelxivjw.supabase.co/functions/v1/cleancontrol-schedules';
async function scheduleApi(action,data={}){const r=await fetch(SCHEDULE_API,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({ok:false,error:'استجابة غير صالحة'}));if(!r.ok||j.ok===false){const e=new Error(j.error||'تعذر تنفيذ طلب الخطة');e.code=j.code;throw e}return j}
const SCHEDULE_DAY_NAMES=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
function scheduleDays(v=[]){return v.map(x=>SCHEDULE_DAY_NAMES[Number(x)]||x).join('، ')}
function dateOnly(v){if(!v)return 'مستمرة';try{return new Date(v+'T12:00:00').toLocaleDateString('ar-JO')}catch{return v}}
function scheduleDate(v){if(!v)return '';try{return new Date(v).toLocaleString('ar-JO',{timeZone:'Asia/Amman'})}catch{return v}}
function companyLogo(){return `<div style="display:flex;align-items:center;gap:14px;border-bottom:2px solid #303887;padding-bottom:10px;margin-bottom:14px"><svg width="90" height="118" viewBox="0 0 90 118" xmlns="http://www.w3.org/2000/svg"><rect width="90" height="118" rx="3" fill="#303887"/><path d="M5 18 C34 48 67 42 88 19 M6 46 C39 70 69 54 89 34 M2 66 C35 65 67 52 89 39" fill="none" stroke="#b9bcc3" stroke-width="3"/><text x="10" y="88" fill="#d0d0d4" font-size="15" font-family="Arial">GLOBE</text><text x="10" y="105" fill="#d0d0d4" font-size="15" font-weight="700" font-family="Arial">WILLIAMS</text></svg><div><div style="font-size:24px;font-weight:800;color:#0b2a55">CleanControl</div><div style="font-size:17px;font-weight:700">GLOBE WILLIAMS INTERNATIONAL</div><div style="font-size:13px">TOTAL FACILITY SERVICES</div></div></div>`}

buildNav=function(){const admin=me?.role==='admin';const buttons=[['home','الرئيسية'],...(!admin?[['mySchedule','خطتي']]:[]),['notes','الملاحظات'],...(admin?[['operations','مركز العمليات'],['checklists','Checklist'],['profiles','المشرفون'],['schedules','خطة الجولات'],['reports','التقارير'],['storage','التخزين'],['audit','سجل التدقيق']]:[]),['settings','الإعدادات']];$('nav').innerHTML=buttons.map(([k,l])=>`<button data-nav="${k}">${l}</button>`).join('')+`<button class="danger" id="logoutBtn">خروج</button>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));$('logoutBtn').onclick=logout};
const _scheduleOldGo=go;go=async function(k){if(k==='mySchedule'){activeNav(k);return mySchedule()}return _scheduleOldGo(k)};
const _scheduleBaseHome=home;home=async function(){await _scheduleBaseHome();if(me?.role!=='supervisor')return;try{const j=await scheduleApi('my_schedule'),today=new Date().toISOString().slice(0,10),active=(j.schedules||[]).filter(s=>!s.end_date||s.end_date>=today);if(active.length){$('view').insertAdjacentHTML('afterbegin',`<div class="card notice"><div class="section-title"><div><b>لديك خطة عمل محفوظة من الإدارة</b><div class="small">${active.length} بند ضمن الخطة الحالية</div></div><button class="primary" onclick="go('mySchedule')">عرض خطتي</button></div></div>`)}}catch{}};

function planTable(rows,supervisorView=false){return `<div class="table-wrap"><table><thead><tr><th>الخطة</th>${supervisorView?'':'<th>المشرف</th>'}<th>المبنى</th><th>الطابق</th><th>الفترة</th><th>الأيام</th><th>الوقت</th><th>إعداد / تعديل</th>${supervisorView?'':'<th>إجراء</th>'}</tr></thead><tbody>${rows.map(s=>`<tr><td><b>${esc(s.plan_name||'خطة الجولات')}</b></td>${supervisorView?'':`<td>${esc(s.profiles?.full_name||'')}</td>`}<td>${esc(s.buildings?.name||'')}</td><td>${esc(s.floors?.label||'كل المبنى')}</td><td>${s.start_date||s.end_date?`${dateOnly(s.start_date)} — ${dateOnly(s.end_date||s.start_date)}`:'مستمرة'}</td><td>${esc(scheduleDays(s.weekdays||[]))}</td><td>${esc(String(s.target_time||s.window_end||'').slice(0,5))}</td><td><div>${s.creator?.full_name?`أعدها ${esc(s.creator.full_name)}`:'الإدارة'}${s.created_at?` • ${scheduleDate(s.created_at)}`:''}</div>${s.editor?.full_name&&s.updated_at&&s.updated_at!==s.created_at?`<div class="small">آخر تعديل: ${esc(s.editor.full_name)} • ${scheduleDate(s.updated_at)}</div>`:''}</td>${supervisorView?'':`<td><div class="actions"><button class="secondary" onclick="editSchedule('${s.id}')">تعديل</button><button class="dark" onclick="printSchedule('${s.id}')">طباعة</button><button class="danger" onclick="deleteSchedule('${s.id}')">حذف</button></div></td>`}</tr>`).join('')}</tbody></table></div>`}

async function mySchedule(){$('view').innerHTML='<div class="card">جاري تحميل خطتك...</div>';try{const j=await scheduleApi('my_schedule'),rows=j.schedules||[];window._ccMySchedules=rows;$('view').innerHTML=`<div class="card"><div class="section-title"><div><h2>خطتي</h2><div class="small">كل خطة يعتمدها الأدمن لك تظهر هنا تلقائيًا.</div></div>${rows.length?'<button class="dark" onclick="printMySchedules()">طباعة الخطة</button>':''}</div>${rows.length?planTable(rows,true):'<div class="notice">لا توجد خطة مسندة لك حاليًا.</div>'}</div>`}catch(e){$('view').innerHTML=`<div class="error">${esc(e.message)}</div>`}}

async function schedules(){$('view').innerHTML='<div class="card">جاري تحميل خطة الجولات...</div>';try{const j=await scheduleApi('list_admin'),rows=j.schedules||[];window._ccSchedules=rows;$('view').innerHTML=`<div class="card"><div class="section-title"><div><h2>خطة الجولات / الديب كلينينج</h2><div class="small">كل خطة تحفظ هنا تظهر للمشرف المعني في صفحة «خطتي» مع اسم من أعدها والتاريخ.</div></div><div class="actions"><button class="primary" onclick="newSchedule()">إضافة خطة</button>${rows.length?'<button class="dark" onclick="printAllSchedules()">طباعة الكل</button>':''}</div></div>${rows.length?planTable(rows,false):'<div class="notice">لا توجد خطط محفوظة.</div>'}</div>`}catch(e){$('view').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
window.newSchedule=async()=>openScheduleEditor(null);
window.editSchedule=async function(id){const s=(window._ccSchedules||[]).find(x=>String(x.id)===String(id));if(!s)return toast('الخطة غير موجودة');return openScheduleEditor(s)};
window.openScheduleEditor=async function(s){let ps;try{ps=(await api('admin_profiles')).profiles.filter(p=>p.role==='supervisor'&&p.active)}catch(e){return toast(e.message)}const bs=boot?.buildings||[],sup=s?.profiles?.username||ps[0]?.username||'',bc=s?.buildings?.code||bs[0]?.code||'',days=new Set((s?.weekdays||[]).map(Number));modal(`<h3>${s?'تعديل الخطة':'إضافة خطة'}</h3><input id="spName" value="${esc(s?.plan_name||'خطة ديب كلينينج')}" placeholder="اسم الخطة"><div style="height:8px"></div><select id="sSup">${ps.map(p=>`<option value="${p.username}" ${p.username===sup?'selected':''}>${esc(p.full_name)}</option>`).join('')}</select><div style="height:8px"></div><select id="sB" onchange="fillSFloors('${esc(s?.floors?.label||'')}')">${bs.map(b=>`<option value="${b.code}" ${b.code===bc?'selected':''}>${esc(b.name)}</option>`).join('')}</select><div style="height:8px"></div><select id="sF"></select><div style="height:8px"></div><div class="row2"><div><div class="small">من تاريخ</div><input id="sStart" type="date" value="${esc(s?.start_date||'')}"></div><div><div class="small">إلى تاريخ</div><input id="sEnd" type="date" value="${esc(s?.end_date||'')}"></div></div><div style="height:8px"></div><div class="row2"><div><div class="small">وقت الجولة</div><input id="sTime" type="time" value="${esc(String(s?.target_time||'').slice(0,5))}"></div><div><div class="small">فترة السماح بالدقائق</div><input id="sGrace" type="number" value="${Number(s?.grace_minutes??60)}" min="0"></div></div><h4>أيام التنفيذ</h4><div class="check-days">${SCHEDULE_DAY_NAMES.map((d,i)=>`<label><input name="sD" type="checkbox" value="${i}" ${days.has(i)?'checked':''}>${d}</label>`).join('')}</div>${s?`<div class="notice" style="margin-top:10px">${s.creator?.full_name?`أنشأها: <b>${esc(s.creator.full_name)}</b> — ${scheduleDate(s.created_at)}`:'أنشأتها الإدارة'}${s.editor?.full_name?`<br>آخر تعديل: <b>${esc(s.editor.full_name)}</b> — ${scheduleDate(s.updated_at)}`:''}</div>`:''}<div class="actions" style="margin-top:12px"><button class="primary" onclick="saveSchedule('${s?.id||''}')">حفظ الخطة</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);fillSFloors(s?.floors?.label||'')};
window.fillSFloors=function(selected=''){const b=(boot?.buildings||[]).find(x=>x.code===$('sB')?.value),fs=b?.floors||[];if($('sF'))$('sF').innerHTML=fs.map(f=>`<option value="${esc(f.label)}" ${f.label===selected?'selected':''}>${esc(f.label)}</option>`).join('')};
window.saveSchedule=async function(id=''){try{const wd=[...document.querySelectorAll('[name=sD]:checked')].map(x=>Number(x.value));await scheduleApi('save',{id:id||null,plan_name:$('spName').value,supervisor_username:$('sSup').value,building_code:$('sB').value,floor_label:$('sF').value,start_date:$('sStart').value||null,end_date:$('sEnd').value||null,weekdays:wd,target_time:$('sTime').value||null,grace_minutes:Number($('sGrace').value||60)});closeModal();toast(id?'تم تعديل الخطة':'تم حفظ الخطة وستظهر للمشرف');schedules()}catch(e){toast(e.message)}};
window.deleteSchedule=async function(id){if(!confirm('حذف هذه الخطة؟'))return;try{await scheduleApi('delete',{id});toast('تم حذف الخطة');schedules()}catch(e){toast(e.message)}};
function printRows(rows,supervisorView){if(!rows.length)return toast('لا توجد خطة للطباعة');const old=$('view').innerHTML;$('view').innerHTML=`<div class="print-target">${companyLogo()}<div style="text-align:center;margin-bottom:14px"><h2 style="margin:0">خطة الجولات / الديب كلينينج</h2><div class="small">تاريخ الطباعة: ${new Date().toLocaleString('ar-JO',{timeZone:'Asia/Amman'})}</div></div>${planTable(rows,supervisorView)}</div>`;setTimeout(()=>{window.print();$('view').innerHTML=old},180)}
window.printSchedule=function(id){const s=(window._ccSchedules||[]).find(x=>String(x.id)===String(id));if(!s)return toast('الخطة غير موجودة');printRows([s],false)};
window.printAllSchedules=function(){printRows(window._ccSchedules||[],false)};
window.printMySchedules=function(){printRows(window._ccMySchedules||[],true)};